import { StickyNavbar } from "@components/Navbar";
import "@styles/globals.css";

export const metadata = {
  title: "DNS KENYA FORUM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StickyNavbar />
        {children}
      </body>
    </html>
  );
}
